version: '3.4'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000   
    environment:
    #env_file:
      #./.env
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_DB=unitum
      - DATABASE_USER=postgres
      - SECRET_KEY = 89712f61b343e5cc606345ade54f8f11
      - ALGORITHM = HS256

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=unitum
    volumes:
      - dbData:/var/lib/postgresql/data

volumes:
  dbData: